spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: umc10th_hackathon_team_b_be

  profiles:
    default: local

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
