spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: umc10th_hackathon_team_b_be

  profiles:
    default: local

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

jwt:
  secret: ${JWT_SECRET:change-this-secret-key-at-least-32-characters-long}
  access-token-expiration-seconds: ${JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:1800}
  refresh-token-expiration-seconds: ${JWT_REFRESH_TOKEN_EXPIRATION_SECONDS:2592000}
  signup-token-expiration-seconds: ${JWT_SIGNUP_TOKEN_EXPIRATION_SECONDS:600}

external:
  kakao:
    local-base-url: https://dapi.kakao.com
    rest-api-key: ${KAKAO_REST_API_KEY}
  open-weather:
    base-url: https://api.openweathermap.org
    api-key: ${OPENWEATHER_API_KEY}